#!/usr/bin/env bash

# Install paru (essential for AUR packages): ⮯
mkdir -vp "$HOME"/.cache/
cd "$HOME"/.cache/ || exit 20
git clone https://aur.archlinux.org/paru.git
cd paru || exit 20
makepkg -si

# Install most dependencies: ⮯
cd "$HOME" || exit 20
git clone https://github.com/nosvagor/dotfiles.git
paru -S - < "$HOME"/dotfiles/misc/packages.lst

# my preferred directory structure, see ~/.config/user-dirs.dirs ⮯
mkdir -vp downloads documents/templates books papers share
mkdir -vp media/music media/images media/videos media/gifs media/screenshots media/recordings

# set up sddm: ⮯
mkdir -vp /etc/sddm.conf.d
ln -sfn "$HOME"/dotfiles/misc/sddm.conf.d/autologin.conf /etc/sddm.conf.d
ln -sfn "$HOME"/dotfiles/misc/sddm.conf.d/hyprland.desktop /usr/share/wayland-sessions
sytemctl enable sddm

# symbolically link most config files: ⮯
mkdir -vp "$HOME"/.config/
ln -sfn "$HOME"/dotfiles/config/* "$HOME"/.config/
ln -sf "$HOME"/dotfiles/bin/* /usr/bin
ln -sf "$HOME"/dotfiles/zshrc "$HOME"/
mv "$HOME"/zshrc "$HOME/.zshrc"

# ensure custom fonts are installed: ⮯
mkdir -vp "$HOME"/.local/share/fonts
cp "$HOME"/dotfiles/fonts/*.zip "$HOME"/.local/share/fonts/
cd "$HOME"/.local/share/fonts/  || exit 20
unzip Albert_Sans.zip
unzip Architects_Daughter.zip
unzip Lora.zip
unzip Archivo.zip
rm ./*.txt
rm ./*.zip

exit 0
