#!/usr/bin/env bash

cd $HOME

git clone https://github.com/nosvagor/dotfiles.git
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
cd $HOME

paru -S - < $HOME/dotfiles/misc/packages.lst

mkdir -vp downloads documents documents/templates books papers share media media/music media/images media/videos media/gifs

ln -sfn $HOME/dotfiles/bin/* /usr/bin

mkdir -vp /etc/sddm.conf.d
ln -sfn ~/dotfiles/misc/sddm.conf.d/autologin.conf /etc/sddm.conf.d
ln -sfn ~/dotfiles/misc/sddm.conf.d/hyprland.desktop /usr/share/wayland-sessions

mkdir -vp $HOME/.config/
ln -sfn $HOME/dotfiles/config/* $HOME/.config/

ln -sf $HOME/dotfiles/misc/.zshrc $HOME

mkdir -vp ~/.local/share/fonts
cp ~/dotfiles/fonts/*.zip ~/.local/share/fonts/
cd ~/.local/share/fonts/
unzip Albert_Sans.zip
rm *.txt
unzip Architects_Daughter.zip
rm *.txt
unzip Lora.zip
rm *.txt
unzip Archivo.zip
rm *.txt
rm *.zip

exit 0
