#!/usr/bin/env bash

for ((i = 1; i < 5; i++)); do
    wget -O "0${i}d.png" "http://openweathermap.org/img/wn/0${i}d@2x.png"
    wget -O "0${i}n.png" "http://openweathermap.org/img/wn/0${i}n@2x.png"
done

wget -O "09d.png" "http://openweathermap.org/img/wn/09d@2x.png"
wget -O "09n.png" "http://openweathermap.org/img/wn/09n@2x.png"

for ((i = 10; i < 14; i++)); do
    if [[ i -ne 12 ]]; then
        wget -O "${i}d.png" "http://openweathermap.org/img/wn/${i}d@2x.png"
        wget -O "${i}n.png" "http://openweathermap.org/img/wn/${i}n@2x.png"
    fi
done

wget -O "50d.png" "http://openweathermap.org/img/wn/50d@2x.png"
wget -O "50n.png" "http://openweathermap.org/img/wn/50n@2x.png"
