#!/usr/bin/env bash

inprog=$(ps -ef | rg adjust | rg -v rg | wc -l)
if [[ "$inprog" -gt 2 ]]; then
    exit 1
fi

reset () {
    echo "10" > "/tmp/eww/brightness"
    pkill wlr-brightness
    sleep 0.1
    wlr-brightness & disown
    notify-send -h int:value:100 "normal brightness (100%)" -u low -t 1000 -i display-brightness-full
    gdbus call -e -d de.mherzberg -o /de/mherzberg/wlrbrightness -m de.mherzberg.wlrbrightness.set 1
}

night () {
    echo "4" > "/tmp/eww/brightness"
    notify-send -h int:value:"$br"0 "low brightness (40%)" -u low -t 1000 -i display-brightness-low
    gdbus call -e -d de.mherzberg -o /de/mherzberg/wlrbrightness -m de.mherzberg.wlrbrightness.set 0.4
}

adjust () {
    br="$2"
    if [[ "$br" -ge 2 ]] && [[ "$br" -le 10 ]]; then
        if [[ "$1" == "down" ]]; then
            if [[ "$br" -gt 2 ]]; then
                gdbus call -e -d de.mherzberg -o /de/mherzberg/wlrbrightness -m de.mherzberg.wlrbrightness.decrease 0.1
                br=$((br - 1))
            fi
        else
            if [[ "$br" -lt 10 ]]; then
                gdbus call -e -d de.mherzberg -o /de/mherzberg/wlrbrightness -m de.mherzberg.wlrbrightness.increase 0.1
                br=$((br + 1))
            fi
        fi
        echo "$br" >> "/tmp/eww/brightness"
        notify-send -h int:value:"$br"0 "brightness ""${br}0%" -u low -t 1000 -i display-brightness-medium
    else
        exit 0
    fi
}

"$@"
