#!/usr/bin/env bash

dir=/tmp/eww
rm -rf "$dir"
mkdir "$dir"
mkdir "$dir/weather"

file_names="workspace sink source clockface-minute clockface-hour date_abd weeks_alive"
read -ra names_arr <<< "$file_names"

for name in "${names_arr[@]}"; do
    touch "$dir/$name"
done

weather_file_names="id icon temp main cond aqi uvi rain wind weather.json"
read -ra weather_names_arr <<< "$weather_file_names"

for name in "${weather_names_arr[@]}"; do
    touch "$dir/weather/$name"
done

echo "13:00" > "$dir/alarm"
echo "01:30" > "$dir/timer"
echo "50" > "$dir/sink"
echo "100" > "$dir/source"

exit 0
