#!/usr/bin/env bash

day () {
    while true; do
        date_abd=$(date +'{"weekday":"%A", "month":"%B", "day":"%d"}')
        echo "$date_abd" >> "/tmp/eww/date_abd"
        until_tomorrow=$(( $(date +%s -d "tomorrow 00:00") - $( date +%s ) ))
        sleep "$until_tomorrow"
    done
}

week () {
    while true; do
        greg_brith="1996-02-26 PST"
        weeks_alive=$(( ($(date -d "$greg_brith" +%s) - $(date +%s))/86400/-7 ))
        echo "$weeks_alive" >> "/tmp/eww/weeks_alive"
        until_monday=$(( $(date +%s -d "next monday 00:00") - $( date +%s ) ))
        sleep "$until_monday"
    done
}

clockface-hour () {
    while true; do
        hour=$(date "+%I")

        case "$hour" in
            01) res="";;
            02) res="";;
            03) res="";;
            04) res="";;
            05) res="";;
            06) res="";;
            07) res="";;
            08) res="";;
            09) res="";;
            10) res="";;
            11) res="";;
            12) res="";;
            *) res="";;
        esac
        echo "$res" >> "/tmp/eww/clockface-hour"
        next_hour=$(date -d "+ 1hour" "+%H:00")
        until_next_hour=$(( $(date -d "$next_hour" +%s) - $(date +%s) ))
        sleep "$until_next_hour"
    done;
}

clockface-minute () {
    while true; do
        minute=$(date "+%M / 5" | bc)
        minute=${minute%.*}

        case "$minute" in
            1) res="";;
            2) res="";;
            3) res="";;
            4) res="";;
            5) res="";;
            6) res="";;
            7) res="";;
            8) res="";;
            9) res="";;
            10) res="";;
            11) res="";;
            12) res="";;
            *) res="";;
        esac
        echo "$res" >> "/tmp/eww/clockface-minute"
        until_next_min=$(( 60 - $(date +%-S) ))
        sleep "$until_next_min"
    done
}

day & week & clockface-hour & clockface-minute
