#!/usr/bin/env bash

player="--player=youtube-music-desktop-app"

# song() {
#     song=$(playerctl --player=youtube-music-desktop-app metadata --format \
#         '{{markup_escape(title)}}' | sed -e 's/([^()]*)//g' -e 's/ $//g' -e 's/:.*//g' -e 's/,.*//g')
#     album=$(playerctl --player=youtube-music-desktop-app metadata --format \
#         '{{markup_escape(album)}}' | sed -e 's/([^()]*)//g' -e 's/ -.*//g' -e 's/ $//g' -e 's/:.*//g')
#
#     if [[ "$song" == "$album" ]]; then
#         echo " <i>$album</i>"
#     else
#         echo " <i>$song</i>  $album"
#     fi
# }
#
# artist() {
#     artist=$(playerctl --player=youtube-music-desktop-app metadata --format \
#         '{{markup_escape(artist)}}')
#
#     echo " <b>$artist</b>"
# }
#
progress() {
    length=$(playerctl "$player" metadata -f '{{ mpris:length }}' | bc)
    position=$(playerctl "$player"  metadata -f '{{ position }}' | bc)
    progress=$(echo "scale=3; $position / $length * 100 + 0.1" | bc)
    echo "$progress"
}
#
# cover() {
#     if [[ "$online" -eq 0 ]] && "$active"; then
#         artUrl=$(playerctl --player=youtube-music-desktop-app metadata --format '{{mpris:artUrl}}')
#         tempfile="/tmp/eww/.album_art.png"
#         wget --output-document="$tempfile" "$artUrl"
#         echo "$tempfile"
#     else
#         echo "/home/cullyn/.config/eww/assets/ytm.png"
#     fi
# }
#
# volume() {
#     volume=$(playerctl volume)
#     volume=$(echo "$volume * 10 / 1" | bc)
#     echo "墳 $volume"
# }
#

get_json () {
    playerctl -F "$player" metadata -f "{\
        \"status\":\"{{ status }}\",\
        \"volume\":\"{{ volume }}\",\
        \"album\":\"{{ album }}\",\
        \"artUrl\":\"{{ mpris:artUrl }}\",\
        \"artist\":\"{{ artist }}\",\
        \"title\":\"{{ title }}\"\
    }"
}

"$@"
