#!/usr/bin/env bash

set_default () {
    sink_val=69
    source_val=100
    source_id="$(get_id "source")"
    sink_id="$(get_id "sink")"

    pulsemixer --id "sink-$sink_id" --set-volume "$sink_val"
    pulsemixer --id "source-$source_id" --set-volume "$source_val"

    echo "$sink_val" >> "/tmp/eww/sink"
    echo "$source_val" >> "/tmp/eww/source"

}

get_id () {
    id=$(pulsemixer --list-"$1" \
        | grep "Default" \
        | gawk "{print \$1}" FPAT="[0-9]+")
    echo "$id"
}

get_volume () {
    id=$(get_id "$1")
    volume=$(pulsemixer --get-volume --id "$1-$id" \
        | gawk "{print \$1}" FPAT="[0-9]+")
    echo "$volume"
}

change_volume () {
    direction="+"
    if [[ "$2" == "down" ]]; then
        direction="-"
    fi
    id="$(get_id "$1")"
    pulsemixer --id "$1-$id" --change-volume "$direction$3"
    get_volume "$1" >> "/tmp/eww/$1"
}

"$@"
