#!/usr/bin/env bash

dir="$HOME/.config/eww/scripts"

eval "$dir/create_temp_files" & disown
eval "$dir/music_info get_json" & disown
eval "$dir/weather_info get_json" & disown
eval "$dir/weather_info continuous" & disown
eval "$dir/pulse_info get_volume sink" & disown
eval "$dir/date_info" & disown

exit 0
