#!/usr/bin/env bash

dir="$HOME/.config/eww/scripts"

"$dir/create_temp_files"

eval "$dir/workspaces" & disown
eval "$dir/date_info continuous" & disown
eval "$dir/weather_info get_json" & disown
eval "$dir/weather_info continuous" & disown
eval "$dir/pulse_info get_volume sink" & disown

exit 0
