#!/usr/bin/env bash

display_active () {
    eww update timer-visible="true"
    case "$1" in
        "hour") eww update hour-active="true" ;;
        "minute") eww update minute-active="true" ;;
    esac
    dunstify -a "attention" -t 1000 "🐦attention"
    sleep 5
    eww update timer-visible="false"
    eww update minute-active="false"
    eww update hour-active="false"
}

timer () {
    IFS=":" read -ra timer <<<"$(tail -n 1 "/tmp/eww/timer")"
    hr=${timer[0]#0}
    min=${timer[1]#0}

    if [[ "$1" == "up" ]]; then
        ((min+=$2))
        if [[ $min -ge 60 ]]; then
            ((hr+=1))
            ((min-=60))
        fi
    elif [[ $hr -gt 0 ]] || [[ $min -gt 0 ]]; then
            ((min-=$2))
    fi

    if [[ $min -lt 0 ]] && [[ $hr -gt 0 ]]; then
        ((hr-=1))
        ((min+=60))
    fi

    if [[ $min -lt 0 ]]; then
        min=0
    fi

    printf "%02d:%02d\n" "$hr" "$min" >> "/tmp/eww/timer"
}

timer_status () {
    dunstify -t 1000 "timer started!"

    countdown=true
    while "$countdown"; do
        IFS=":" read -ra timer <<<"$(tail -n 1 "/tmp/eww/timer")"
        hr=${timer[0]#0}
        min=${timer[1]#0}

        if [[ $hr -eq 0 ]] && [[ $min -eq 0 ]]; then
            countdown=false
            dunstify -a "timer" "timer done!"
            display_active "minute"
            break
        fi

        if [[ $((min % 15)) -eq 0 ]] || [[ $min -le 5 ]]; then
            display_active "minute"
        fi

        until_next_min=$(( 60 - $(date +%-S) ))
        sleep "$until_next_min"
        timer "down" 1
    done
}

alarm () {
    IFS=":" read -ra alarm <<<"$(tail -n 1 "/tmp/eww/alarm")"
    hr=${alarm[0]#0}
    min=${alarm[1]#0}

    if [[ "$1" == "start" ]]; then
        hr_now=$(date '+%H')
        min_now=$(date '+%M')
        ((hr-=hr_now))
        ((min-=min_now))
    fi

    if [[ "$1" == "up" ]]; then
        ((min+=$2))
        if [[ $min -ge 60 ]]; then
            ((hr+=1))
            ((min-=60))
        fi
    elif [[ $hr -gt 0 ]] || [[ $min -gt 0 ]]; then
            ((min-=$2))
    fi

    if [[ $min -lt 0 ]] && [[ $hr -gt 0 ]]; then
        ((hr-=1))
        ((min+=60))
    fi

    if [[ $hr -ge 24 ]]; then
        ((hr-=24))
    fi

    if [[ $min -lt 0 ]]; then
        ((hr+=min))
        min=0
    fi

    printf "%02d:%02d\n" "$hr" "$min" >> "/tmp/eww/alarm"
}


alarm_status () {
    dunstify -t 1000 "alarm started!"

    alarm "start"

    countdown=true
    while "$countdown"; do
        IFS=":" read -ra timer <<<"$(tail -n 1 "/tmp/eww/alarm")"
        hr=${timer[0]#0}
        min=${timer[1]#0}

        if [[ $hr -eq 0 ]] && [[ $min -eq 0 ]]; then
            countdown=false
            dunstify -a "timer" "alarm done!"
            display_active "hour"
            break
        fi

        if [[ $((min % 15)) -eq 0 ]] || [[ $min -le 5 ]]; then
            display_active "hour"
        fi

        until_next_min=$(( 60 - $(date +%-S) ))
        sleep "$until_next_min"
        alarm "down" 1
    done
}


reset () {
    case "$1" in
        alarm)
            ps -ef | rg alarm_status | rg -v rg | awk '{print $2}' | xargs kill
            next_hour=$(date -d "+ 1hour" "+%H:00")
            until_next_hour=$(( $(date -d "$next_hour" +%s) - $(date +%s) ))
            (( until_next_hour/=60 ))
            if [[ $until_next_hour -lt 30 ]]; then
                offset="+ 4hour"
            else
                offset="+ 3hour"
            fi
            date '+%H:00' -d "$offset" > "/tmp/eww/alarm"
            dunstify -t 1000 "alarm reset"
        ;;
        timer)
            ps -ef | rg timer_status | rg -v rg | awk '{print $2}' | xargs kill
            echo "01:30" > "/tmp/eww/timer"
            dunstify -t 1000 "timer reset"
        ;;
    esac

}

"$@"
