#!/usr/bin/env bash

get_json () {
    lat="45.491848"
    lon="-122.688451"
    api=$(cat /home/cullyn/.openweather_api_key)
    units="metric"
    weahterUrl="https://api.openweathermap.org/data/3.0/onecall?lat=$lat&lon=$lon&units=$units&appid=$api"

    while true; do
        curl "$weahterUrl" | jq > "/tmp/.weather_info.json"
        sleep 300
    done
}

get_time () {
    time=$(jq -r ".current.$1" '/tmp/.weather_info.json')
    date -d @"$time" +%H:%M
}

"$@"
