#!/usr/bin/env bash

DIR=/tmp/eww
WEATHER_JSON="$DIR/open-weather.json"
AIR_JSON="$DIR/air.json"
WAIT=60
valid_json="false"

read -ra location <<<"$(<"$HOME/.local/.location")"
LAT="${location[0]}"
LON="${location[1]}"
API=$(<"$HOME/.local/.owm_api_key")
UNITS="metric"
WEATHER_URL="https://api.openweathermap.org/data/3.0/onecall?lat=$LAT&lon=$LON&units=$UNITS&exclude=hourly,daily,minutely&appid=$API"

online=1
connection () {
    nc -z 8.8.8.8 53  >/dev/null 2>&1
    online=$?
}

get_json () {
    while [[ "$online" -eq 1 ]]; do
        valid_json="false"
        connection
        sleep 0.5
    done

    start=$(date "+%s")
    end=$(( start + 5000 ))
    air_url="http://api.openweathermap.org/data/2.5/air_pollution/history?lat=$LAT&lon=$LON&start=$start&end=$end&appid=$API"

    curl "$WEATHER_URL" | jq > "$WEATHER_JSON"
    curl "$air_url" | jq > "$AIR_JSON"
    valid_json="true"
}

while true; do
    while [[ "$valid_json" == "false" ]] ; do
        get_json
    done

    id=$(jq -r ".current.weather[0].id" "$WEATHER_JSON")
    desc=$(jq -r ".current.weather[0].main" "$WEATHER_JSON")
    sunrise=$(jq -r ".current.sunrise" "$WEATHER_JSON")
    sunrise=$(date -d @"$sunrise" +"%H:%M")
    sunset=$(jq -r ".current.sunset" "$WEATHER_JSON")
    now=$(date "+%s")
    if [[ "$now" -gt "$sunset" ]]; then
        night="true"
    else
        night="false"
    fi
    sunset=$(date -d @"$sunset" +"%H:%M")
    temp=$(jq -r ".current.temp" "$WEATHER_JSON")
    feels_like=$(jq -r ".current.feels_like" "$WEATHER_JSON")
    uvi=$(jq -r ".current.uvi" "$WEATHER_JSON")
    clouds=$(jq -r ".current.clouds" "$WEATHER_JSON")

    wind_speed=$(jq -r ".current.wind_speed" "$WEATHER_JSON")
    wind_deg=$(jq -r ".current.wind_deg" "$WEATHER_JSON")
    knots=$(echo "$wind_speed * 1.943844" | bc)
    knots=$(echo "$knots" | awk '{print int($1+0.5)}')

    if [[ "$night" == "false" ]]; then
        if [[ "$id" -lt 300 ]]; then
            icon=" "
        elif [[ "$id" -lt 500 ]]; then
            icon=" "
        elif [[ "$id" -eq 504 ]]; then
            icon=" "
        elif [[ "$id" -lt 600 ]]; then
            icon=" "
        elif [[ "$id" -lt 700 ]]; then
            icon=" "
        elif [[ "$id" -eq 711 ]]; then
            icon=" "
        elif [[ "$id" -eq 781 ]]; then
            icon=" "
        elif [[ "$id" -eq 800 ]]; then
            icon=" "
        elif [[ "$id" -eq 800 ]]; then
            icon=" "
        elif [[ "$id" -lt 803 ]]; then
            icon=" "
        else
            icon=" "
        fi
    else
        if [[ "$id" -lt 300 ]]; then
            icon=" "
        elif [[ "$id" -lt 500 ]]; then
            icon=" "
        elif [[ "$id" -eq 504 ]]; then
            icon=" "
        elif [[ "$id" -lt 600 ]]; then
            icon=" "
        elif [[ "$id" -lt 700 ]]; then
            icon=" "
        elif [[ "$id" -eq 711 ]]; then
            icon=" "
        elif [[ "$id" -eq 781 ]]; then
            icon=" "
        elif [[ "$id" -lt 800 ]]; then
            icon=" "
        elif [[ "$id" -eq 800 ]]; then
            icon=" "
        elif [[ "$id" -lt 803 ]]; then
            icon=" "
        else
            icon=" "
        fi
    fi

    if [[ knots -lt 1 ]]; then
        bf_icon=" "
        bf_desc="calm"
    elif [[ knots -lt 4 ]]; then
        bf_icon=" "
        bf_desc="light air"
    elif [[ knots -lt 7 ]]; then
        bf_icon=" "
        bf_desc="light breeze"
    elif [[ knots -lt 11 ]]; then
        bf_icon=" "
        bf_desc="gentle breeze"
    elif [[ knots -lt 17 ]]; then
        bf_icon=" "
        bf_desc="moderate breeze"
    elif [[ knots -lt 22 ]]; then
        bf_icon=" "
        bf_desc="fresh breeze"
    elif [[ knots -lt 28 ]]; then
        bf_icon=" "
        bf_desc="strong breeze"
    elif [[ knots -lt 34 ]]; then
        bf_icon=" "
        bf_desc="near gale"
    elif [[ knots -lt 41 ]]; then
        bf_icon=" "
        bf_desc="gale"
    elif [[ knots -lt 48 ]]; then
        bf_icon=" "
        bf_desc="strong gale"
    elif [[ knots -lt 56 ]]; then
        bf_icon=" "
        bf_desc="storm"
    elif [[ knots -lt 64 ]]; then
        bf_icon=" "
        bf_desc="violent storm"
    else
        bf_icon=" "
        bf_desc="hurricane"
    fi

    if [[ $wind_deg -lt 45 ]]; then
        wind_icon=" "
        wind_dir="N"
    elif [[ $wind_deg -lt 90 ]]; then
        wind_icon=" "
        wind_dir="NE"
    elif [[ $wind_deg -lt 135 ]]; then
        wind_icon=" "
        wind_dir="E"
    elif [[ $wind_deg -lt 225 ]]; then
        wind_icon=" "
        wind_dir="SE"
    elif [[ $wind_deg -lt 180 ]]; then
        wind_icon=" "
        wind_dir="S"
    elif [[ $wind_deg -lt 225 ]]; then
        wind_icon=" "
        wind_dir="SW"
    elif [[ $wind_deg -lt 270 ]]; then
        wind_icon=" "
        wind_dir="W"
    elif [[ $wind_deg -lt 315 ]]; then
        wind_icon=" "
        wind_dir="NW"
    else
        wind_icon=" "
        wind_dir="N"
    fi

    echo "{\
        \"id\":\"$id\",\
        \"icon\":\"$icon\",\
        \"desc\":\"$desc\",\
        \"bf_icon\":\"$bf_icon\",\
        \"bf_desc\":\"$bf_desc\",\
        \"wind_icon\":\"$wind_icon\",\
        \"wind_speed\":\"$wind_speed\",\
        \"wind_deg\":\"$wind_deg\",\
        \"wind_dir\":\"$wind_dir\",\
        \"sunrise\":\"$sunrise\",\
        \"sunset\":\"$sunset\",\
        \"night\":\"$night\",\
        \"temp\":\"$temp\",\
        \"feels_like\":\"$feels_like\",\
        \"uvi\":\"$uvi\",\
        \"clouds\":\"$clouds\"\
    }" > '/tmp/eww/weather.json'

    sleep "$WAIT"
done
