#!/usr/bin/env bash

handle() {
    if [[ "$1" == "workspace" ]]; then
        # appending (>>) only works, truncating (>) seems to miss events sometimes
        echo "$2" >> "/tmp/eww/workspace"
    fi
}

next_or_prev () {
    direction="+1"
    if [[ "$1" == "down" ]]; then
        direction="-1"
    fi
    hyprctl dispatch workspace "e$direction"
}

if [[ -n "$1" ]]; then
    "$@"
fi

socat - UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock \
    | while read -r line; do
        line=${line/>>/ }
        read -ra hyprland_event <<< "$line"
        handle "${hyprland_event[@]}"
    done
