#!/usr/bin/env bash

tempfile="/tmp/.active_workspace"

handle() {
    event=$1
    arg=$2
    if [[ "$event" == "workspace" ]]; then
        echo "$arg" >> "$tempfile" # needed for 'tail -f'
        echo "$arg" > "$tempfile" # so tempfile doesn't grow
    fi
}

socat - UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock \
    | while read -r line; do
        line=${line/>>/ }
        read -ra hyprland_event <<< "$line"
        handle "${hyprland_event[@]}"
    done
