#!/usr/bin/env bash

handle() {
    event=$1
    arg=$2
    if [[ "$event" == "workspace" ]]; then
        echo "$arg" >> "/tmp/eww/workspace"
    fi
}

socat - UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock \
    | while read -r line; do
        line=${line/>>/ }
        read -ra hyprland_event <<< "$line"
        handle "${hyprland_event[@]}"
    done
