#!/bin/sh

# needs https://github.com/wmutils/opt
# see https://github.com/wmutils/opt/issues/48 if issue with borders.

outer='0x121317'   # outer
inner1='0xff9430'  # focused
inner2='0x9ecbf7'  # normal

targets() {
	case $1 in
		focused) bspc query -N -n .local.focused.\!fullscreen;;
		normal)  bspc query -N -n .local.\!focused.\!fullscreen;;
		active) bspc query -N -n .active.\!focused.\!fullscreen
	esac
}

draw() { chwb2 -I "$i" -O "$o" -i "1" -o "10" $@ 2> /dev/null; }

# initial draw, and then subscribe to events
{ echo; bspc subscribe node_geometry node_focus; } |
	while read -r _; do
		i=$inner1 o=$outer draw "$(targets focused)"
		i=$inner2 o=$outer draw "$(targets  normal)"
		i=$inner2 o=$outer draw "$(targets  active)"		
	done
