#! /bin/sh
# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
# →-.   →  .-'.   →  .--.   →  .--.   →  .--.   →  .-→
# →::.\::::::::.\::::::::.\::::::::.\::::::::.\::::::: → →
# → →:.\ https://github.com/nosvagor/dotfiles \::: → →  →  →
# →::::.\::::::::.\::::::::.\::::::::.\::::::::.\::::→  →
#   → →   `--'  →   `.-'  →   `--'  →   `--'  →   `--' → →

# ╔═╗┬ ┬┌┬┐┌─┐┌─┐┌┬┐┌─┐┬─┐┌┬┐
# ╠═╣│ │ │ │ │└─┐ │ ├─┤├┬┘ │
# ╩ ╩└─┘ ┴ └─┘└─┘ ┴ ┴ ┴┴└─ ┴
bspc rule -r '*'
killall "dunst"
dunst &
killall "sxhkd"
sxhkd &
killall "lxsession"
lxsession &
~/.config/polybar/launch.sh &
killall "borders"
~/.config/bspwm/borders &
# killall "discord"
# killall "ytmdesktop"
# killall "electron"
# discord &
ytmdesktop &

# ╦═╗┬ ┬┬  ┌─┐┌─┐
# ╠╦╝│ ││  ├┤ └─┐
# ╩╚═└─┘┴─┘└─┘└─┘
bspc monitor -d 1 2 3 4 5 6
bspc rule -a youtube-music-desktop-app desktop='^6'
bspc rule -a Gpick state=floating
bspc rule -a Peek state=floating
bspc rule -a Zathura state=tiled
bspc rule -a vlc state=floating
bspc rule -a zoom state=floating
bspc rule -a Inkscape state=floating
bspc rule -a discord desktop='^1'

# ╔═╗┌─┐┌┐┌┌─┐┬┌─┐
# ║  │ ││││├┤ ││ ┬
# ╚═╝└─┘┘└┘└  ┴└─┘
bspc config split_ratio             0.52
bspc config border_width            10
bspc config focused_border_color    '#161821'
bspc config window_gap              9
bspc config top_padding             56
bspc config right_padding           6
bspc config left_padding            6
bspc config bottom_padding          10

bspc config presel_feedback         false
bspc config focus_follows_pointer   true

bspc config single_monocle          true
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config paddingless_monocle     false
bspc config top_monocle_padding     147
bspc config right_monocle_padding   302
bspc config left_monocle_padding    302
bspc config bottom_monocle_padding  100

sleep 1 && notify-send -t 6000 "$USER@$HOSTNAME" "こんにちは" --icon="$HOME/dotfiles/resources/nosvagor.png"
