#! /bin/sh
# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
# →-.   →  .-'.   →  .--.   →  .--.   →  .--.   →  .-→
# →::.\::::::::.\::::::::.\::::::::.\::::::::.\::::::: → →
# → →:.\ https://github.com/nosvagor/.dotfiles \::: → →  →  →
# →::::.\::::::::.\::::::::.\::::::::.\::::::::.\::::→  →
#   → →   `--'  →   `.-'  →   `--'  →   `--'  →   `--' → →

# ╔═╗┬ ┬┌┬┐┌─┐┌─┐┌┬┐┌─┐┬─┐┌┬┐
# ╠═╣│ │ │ │ │└─┐ │ ├─┤├┬┘ │
# ╩ ╩└─┘ ┴ └─┘└─┘ ┴ ┴ ┴┴└─ ┴
bspc rule -r '*'
killall "dunst"
dunst &
killall "sxhkd"
sxhkd &
killall "lxsession"
lxsession &
~/.config/polybar/launch.sh &
killall "borders"
~/.config/bspwm/borders &
pkill "inkscape-figures"
inkscape-figures watch &
python3 $HOME/.local/bin/inktex/main.py &
ytmdesktop &

# ╦═╗┬ ┬┬  ┌─┐┌─┐
# ╠╦╝│ ││  ├┤ └─┐
# ╩╚═└─┘┴─┘└─┘└─┘
bspc monitor -d 1 2 3 4 5 6
bspc rule -a youtube-music-desktop-app desktop='^6'
bspc rule -a Gpick state=floating
bspc rule -a Zathura state=tiled
bspc rule -a vlc state=floating
bspc rule -a zoom state=floating
bspc rule -a Inkscape state=floating

# ╔═╗┌─┐┌┐┌┌─┐┬┌─┐
# ║  │ ││││├┤ ││ ┬
# ╚═╝└─┘┘└┘└  ┴└─┘
bspc config split_ratio             0.75
bspc config border_width            10
bspc config window_gap              9
bspc config top_padding             52
bspc config right_padding           6
bspc config left_padding            6
bspc config bottom_padding          4

bspc config presel_feedback         false

bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config paddingless_monocle     false
bspc config top_monocle_padding     100
bspc config right_monocle_padding   400
bspc config left_monocle_padding    400
bspc config bottom_monocle_padding  100

bspc config focus_follows_pointer   true

sleep 1 && notify-send -t 3000 $USER hello
