eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

function command_not_found_handler {
    return 127
}

export TERM=xterm-256color

if [ -f "$HOME/.anthropic_api_key" ]; then
  export ANTHROPIC_API_KEY=$(cat "$HOME/.anthropic_api_key")
fi

# history
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=800
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt AUTO_CD

# aliases
alias niol='clear && source ~/.zshrc'
alias ls='echo; lsd'
alias n='nvim'
alias c='calc'
alias zz='cd ~'
alias m="make"
alias g='cd "$(xplr --print-pwd-as-result)"'
alias d='cd ~/dotfiles'
alias D='cd ~/downloads'
alias v='cd ~/vagari'
alias e='cd ~/dotfiles/config/nvim'
alias x='exit'
alias p='paru'
alias update='paru -Syu && paru -Qqe > ~/dotfiles/etc/packages.lst'
alias oc='ouch compress'
alias od='ouch decompress'
alias ol='ouch list --tree'
alias man='man --pager=$PAGER'
alias zoomfix='env XDG_CURRENT_DESKTOP=GNOME GDK_BACKEND=x11 QT_QPA_PLATFORM=xcb XDG_SESSION_TYPE=x11 zoom & disown'
alias af='GDK_BACKEND=x11 QT_QPA_PLATFORM=xcb audacity & disown'
function tree () {
    echo
    if [[ -z $1 ]]; then
        L=2
    else
        L=$1
    fi
    erd -L "$L" -I --suppress-size --threads 16 --layout inverted
}

alias ew='eww-open'
alias ews='eww inspector & disown && exit'
alias el='eww logs'

# plugins
if [[ ! -f ${ZDOTDIR:-${HOME}}/.zcomet/bin/zcomet.zsh ]]; then
    command git clone https://github.com/agkozak/zcomet.git ${ZDOTDIR:-${HOME}}/.zcomet/bin
fi
source ${ZDOTDIR:-${HOME}}/.zcomet/bin/zcomet.zsh

zcomet load zsh-users/zsh-completions
zcomet load zsh-users/zsh-autosuggestions
zcomet load marlonrichert/zsh-autocomplete
zcomet load zsh-users/zsh-syntax-highlighting

autoload -U compinit; compinit

ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20

# fix keys
bindkey -v
export KEYTIMEOUT=01
bindkey '^[[H'     vi-beginning-of-line
bindkey '^[[F'     vi-end-of-line
bindkey '^[[3~'    delete-char
bindkey '^[[1;5C'  forward-word   # C-left
bindkey '^[[1;5D'  backward-word  # C-right
bindkey '^[[1;5A'  history-incremental-search-backward # C-up
bindkey '^[[1;5B'  history-incremental-search-forward  # C-down

source $HOME/.config/zsh/vagari-highlights.zsh
