#!/bin/bash

read -p 'Enter the number of your files to create: [ENTER]: ' file_number
read -p 'Enter the name of your file: [ENTER]: ' file_name
read -p 'Enter file extention: [ENTER]: ' file_ext

for ((i = 1; i < file_number + 1; i++))
do
    : > "$file_name$i.$file_ext"
done

